// Language content for landing page
const languageContent = {
  "en": {
  // Navbar & common
  "nav_problem": "Problem",
  "nav_solution": "Solution",
  "nav_trusted": "Trusted",
  "nav_demo": "Demo",
  "nav_faq": "FAQ",
  "nav_about": "About",
  "nav_login": "Login",
  "nav_live_control": "Live Control",
  "lang_popup_title": "Choose Language",
    "hero_title": "Stop Revenue Leakages. Start Capturing Every Rupee.",
    "cta_call_label": "Call Now for Free Testing",
    "cta_call_number": "+91 98765 43210",
    "cta_demo_label": "Book a Live Demo",
  "hero_badge": "🏨 Trusted by Smart Hotels",
  "hero_subtitle": "InnSync is the only PMS with real-time IoT verification, so you never lose a rupee to unrecorded stays or manual errors.",
  "hero_trust": "Already trusted by 20+ hotels in India",
  "hero_pill1": "100% Data Transparency",
  "hero_pill2": "Instant Alerts",
  "hero_pill3": "No More Revenue Leakages",
    "problem_heading": "Are You Losing Money Without Realizing It?",
    "problem_points": [
      "Reception takes cash, no entry in PMS",
      "Room is occupied, dashboard says ‘Vacant’",
      "Owner revenue quietly slips away"
    ],
    "solution_heading": "How InnSync Solves This for You",
    "solution_points": [
      "IoT sensors detect real presence in each room",
      "Data streams to your PMS dashboard in real time",
      "Algorithm cross-checks occupancy vs bookings and flags mismatches"
    ],
    "benefits_heading": "Why Hotel Owners Choose InnSync",
    "benefits_points": [
      "Full visibility: live occupancy, bookings, and revenue",
      "Instant alerts for unrecorded stays",
      "Stop revenue leakages across cash and walk-ins",
      "Works with major booking platforms"
    ],
    "how_heading": "How It Works",
    "how_steps": [
      "Bookings flow in from OTAs and direct channels",
      "Sensors detect occupancy in real time",
      "System cross-checks data automatically",
      "Owner gets instant alert if something’s wrong"
    ],
    "testimonial_heading": "Already in Pilot with Leading Hotels",
    "testimonial_quote": "With InnSync, I finally know exactly what’s happening in my property—no more blind spots.",
    "testimonial_cite": "Rohit Sharma, Hotel Owner, Bangalore",
    "cta_repeat_heading": "Ready to See InnSync in Action?",
    "cta_repeat_body": "Call us now for a free testing period—see how much money you could be saving.",
    "footer_tagline": "InnSync – Helping hotel owners protect every rupee, every room, every day.",
    "lang_label": "Language"
    ,
    // Live Control
    "live_title": "Live Control Panel",
    "live_status_demo": "Demo",
    "live_kpi_occupancy": "Occupancy",
    "live_kpi_registered": "Registered",
    "live_kpi_leakage": "Leakage",
    "live_alert_title": "Leak Alert: 2 rooms occupied but not booked",
    "live_alert_desc": "IoT sensors flagged Room 204, 311 • Action needed",
    "live_bullets": [
      "IoT sensors detect unregistered bookings",
      "Integrations with all major OTA platforms",
      "Intuitive dashboards for owners & managers"
    ],
    // Problem
    "problem_title": "The Problem",
    "problem_text": "Full rooms, empty records. Walk-ins with no trace. Manual updates that never happen. Without real visibility, 10%+ of revenue disappears into thin air.",
    "problem_point1": "Rooms occupied but not recorded",
    "problem_point2": "Untracked walk-ins and staff errors",
    "problem_point3": "Dashboards that don’t match reality",
    "risk_title": "Monthly Risk Snapshot",
    "risk_label1": "Unrecorded Nights",
    "risk_label2": "Monthly Loss",
    "risk_label3": "Occupancy Gap",
    // Solution & pricing
    "solution_title": "How InnSync Stops the Leak",
    "solution_tagline": "Every booking counted. Real-time control. Seamless operations.",
    "sol_card1_title": "IoT Occupancy Sensors",
    "sol_card1_desc": "Detect unregistered stays instantly—no cameras, no PII. If a room is used but not booked, you’ll know.",
    "sol_card2_title": "All OTA Integrations",
    "sol_card2_desc": "Sync reservations across OYO, Booking.com, MakeMyTrip, Agoda, Airbnb & more—no manual entry.",
    "sol_card3_title": "Intuitive Dashboards",
    "sol_card3_desc": "Live occupancy, revenue, and discrepancies for owners & managers. Make decisions with confidence.",
    "pricing_title": "Pricing",
    "pricing_headline": "Grow revenue by 10%+ for just ₹150/month",
    "pricing_sub": "Flat, transparent, no hidden charges.",
    "pricing_tag1": "No long contracts",
    "pricing_tag2": "Easy install",
    "pricing_tag3": "24×7 support",
    "call_now_btn": "Call Now",
    "pricing_demo_btn": "Book a Free Demo",
    // Trust & features
    "trust_title": "Built for trust. Designed for results.",
    "trust_subtitle": "Operational integrity baked in — security, accountability, and uptime that hotels can rely on.",
    "trust_item1_title": "End‑to‑end encryption",
    "trust_item1_desc": "In transit and at rest",
    "trust_item2_title": "Owner‑first visibility",
    "trust_item2_desc": "Every room, every day",
    "trust_item3_title": "99.9% uptime",
    "trust_item3_desc": "Monitored 24×7",
    "trust_item4_title": "Audit logs",
    "trust_item4_desc": "Full trail of changes",
    "ft_trio1_title": "Leak alerts under 60s",
    "ft_trio1_desc": "From sensor to phone",
    "ft_trio2_title": "100% audit trail",
    "ft_trio2_desc": "Every change recorded",
    "ft_trio3_title": "Auto‑reconciliation",
    "ft_trio3_desc": "Daily OTA cross‑checks",
    // Trusted By
    "trusted_title": "Trusted By",
    "trusted_subtitle": "Leading hospitality brands rely on InnSync",
    "how_timeline": [
      {"title": "Connect", "desc": "Connect your hotel to InnSync in minutes—no tech skills needed.", "icon": "🔗"},
      {"title": "Detect", "desc": "IoT sensors detect real occupancy and send data to your dashboard.", "icon": "📡"},
      {"title": "Verify", "desc": "Our algorithm matches bookings with occupancy and flags mismatches.", "icon": "🤖"},
      {"title": "Alert", "desc": "Get instant alerts for unrecorded stays or suspicious activity.", "icon": "⚡"}
    ],
    "testimonial_heading": "What Our Customers Say",
    "testimonials": [
      {"quote": "With InnSync, I finally know exactly what’s happening in my property—no more blind spots.", "cite": "Rohit Sharma, Hotel Owner, Bangalore"},
      {"quote": "Revenue leakages have dropped to zero. The alerts are a game changer!", "cite": "Priya Desai, Blue Lagoon"},
      {"quote": "Setup was so easy, and now I have full control over my hotel’s revenue.", "cite": "Amit Verma, Urban Nest"},
      {"quote": "IoT verification ended disputes about occupancy.", "cite": "Seema Kapoor, Royal Stay"},
      {"quote": "Alerts help my team act instantly—no more manual chasing.", "cite": "Vikram Rao, Front Office Manager"},
      {"quote": "We recovered missed revenue within the first week.", "cite": "Neha Gupta, Owner, Pune"},
      {"quote": "Integration was painless with our existing PMS.", "cite": "Karan Mehta, GM, Beachside Inn"},
      {"quote": "The dashboard is simple and shows what matters.", "cite": "Anita Iyer, Boutique Hotel"},
      {"quote": "InnSync pays for itself—leakages just stopped.", "cite": "Rahul Jain, Multi-property Owner"}
    ],
    "login_title": "Login to Demo",
    "login_subtitle": "Use sample credentials:",
    "login_email_label": "Email",
    "login_password_label": "Password",
    "login_owner_btn": "Login as Owner",
    "login_manager_btn": "Login as Manager",
  "login_terms": "By logging in, you agree to the demo terms. Data is sample only.",
  "feature1_title": "IoT-Powered Room Monitoring",
  "feature1_desc": "Smart sensors track real occupancy, not just bookings.",
  "feature2_title": "Instant Revenue Alerts",
  "feature2_desc": "Get notified the moment a mismatch or leak is detected.",
  "feature3_title": "Owner-First Dashboard",
  "feature3_desc": "See live occupancy, bookings, and revenue in one place.",
  "usecase1_title": "Catch Every Walk-in",
  "usecase1_desc": "No more unrecorded stays—every guest is tracked automatically.",
  "usecase2_title": "Owner Control",
  "usecase2_desc": "Owners get instant alerts and full visibility, even remotely.",
  "usecase3_title": "Easy Integration",
  "usecase3_desc": "Works with your existing PMS and booking platforms.",
  "faq_heading": "Frequently Asked Questions",
  "faq_q1": "How does InnSync prevent revenue leakages?",
  "faq_a1": "InnSync uses IoT sensors and smart algorithms to match real occupancy with bookings, instantly flagging any mismatch or unrecorded stay.",
  "faq_q2": "Is InnSync easy to set up in my hotel?",
  "faq_a2": "Yes! Most hotels are up and running in under 30 minutes. No technical skills required.",
  "faq_q3": "Does InnSync work with my existing PMS?",
  "faq_a3": "InnSync is designed to integrate with major PMS and booking platforms. Contact us for details.",
  "feedback_heading": "Share Your Feedback",
  "feedback_label": "Your feedback helps us improve:",
  "feedback_placeholder": "Type your thoughts, suggestions, or questions here...",
  "feedback_submit": "Send Feedback",
  "feedback_success": "Thank you for your feedback!"
  ,
  // Demo
  "demo_title": "Book a Free Demo",
  "demo_subtitle": "Tell us a bit about your property and we’ll show you how InnSync pays for itself.",
  "demo_name_label": "Your Name",
  "demo_name_placeholder": "John Doe",
  "demo_hotel_label": "Hotel/Property Name",
  "demo_hotel_placeholder": "Sunrise Residency",
  "demo_email_label": "Work Email",
  "demo_email_placeholder": "you@example.com",
  "demo_phone_label": "Phone",
  "demo_phone_placeholder": "+91 98765 43210",
  "demo_city_label": "City (optional)",
  "demo_city_placeholder": "Bengaluru",
  "demo_cancel": "Cancel",
  "demo_submit": "Submit",
  "demo_submit_label": "Request Demo",
  "demo_or_call_text": "Or call us directly at",
  "demo_success": "Thanks! We'll reach out to schedule your demo.",
  "demo_error_name": "Please enter a valid name",
  "demo_error_hotel": "Please enter a valid hotel name",
  "demo_error_email": "Please enter a valid email",
  "demo_error_phone": "Please enter a valid phone number",
  "demo_success_title": "Request received",
  "demo_success_body": "Thanks! We'll get in touch shortly to schedule your live demo.",
  "demo_call_title": "Prefer talking?",
  "demo_call_hours": "Call between 9 AM – 5 PM, all days",
  "demo_call_number_label": "Call {number}"
  },
  "hi": {
  // Navbar & common
  "nav_problem": "समस्या",
  "nav_solution": "समाधान",
  "nav_trusted": "विश्वास",
  "nav_demo": "डेमो",
  "nav_faq": "प्रश्न",
  "nav_about": "About",
  "nav_login": "लॉगिन",
  "nav_live_control": "Live Control",
  "lang_popup_title": "भाषा चुनें",
    "hero_title": "राजस्व लीकेज रोकें। हर रुपया कैप्चर करें।",
    "cta_call_label": "फ्री टेस्टिंग के लिए अभी कॉल करें",
    "cta_call_number": "+91 98765 43210",
    "cta_demo_label": "लाइव डेमो बुक करें",
    "problem_heading": "क्या आप अनजाने में पैसा खो रहे हैं?",
    "problem_points": [
      "रिसेप्शन नकद लेता है, PMS में एंट्री नहीं",
      "कमरा भरा है, डैशबोर्ड ‘Vacant’ दिखाता है",
      "मालिक का राजस्व चुपचाप कम हो जाता है"
    ],
    "solution_heading": "InnSync इसे कैसे हल करता है",
    "solution_points": [
      "हर कमरे में मानव उपस्थिति के लिए IoT सेंसर",
      "डेटा रियल-टाइम में आपके PMS डैशबोर्ड पर पहुंचता है",
      "एल्गोरिदम ऑक्युपेंसी बनाम बुकिंग का मिलान कर तुरंत फ़्लैग करता है"
    ],
    "benefits_heading": "होटल मालिक InnSync क्यों चुनते हैं",
    "benefits_points": [
      "पूरी विज़िबिलिटी: लाइव ऑक्युपेंसी, बुकिंग और रेवेन्यू",
      "अनरिकॉर्डेड स्टे पर तुरंत अलर्ट",
      "कैश और वॉक-इन में लीकेज रोकें",
      "मुख्य बुकिंग प्लेटफ़ॉर्म के साथ काम करता है"
    ],
    "how_heading": "यह कैसे काम करता है",
    "how_steps": [
      "OTAs और डायरेक्ट चैनलों से बुकिंग आती हैं",
      "सेंसर रियल-टाइम में ऑक्युपेंसी पकड़ते हैं",
      "सिस्टम अपने-आप डेटा का मिलान करता है",
      "गड़बड़ी होने पर मालिक को तुरंत अलर्ट मिलता है"
    ],
    "testimonial_heading": "अग्रणी होटलों में पायलट पर",
    "testimonial_quote": "InnSync के साथ मुझे अपनी प्रॉपर्टी की पूरी तस्वीर दिखती है—अब कोई ब्लाइंड स्पॉट नहीं।",
    "testimonial_cite": "रोहित शर्मा, होटल मालिक, बेंगलुरु",
    "cta_repeat_heading": "InnSync को लाइव देखना चाहते हैं?",
    "cta_repeat_body": "अभी कॉल करें—फ्री टेस्टिंग पाएं और देखें कितनी बचत हो सकती है।",
    "footer_tagline": "InnSync – हर रुपया, हर कमरा, हर दिन सुरक्षित।",
    "lang_label": "भाषा"
    ,
    "hero_badge": "🏨 स्मार्ट होटलों की पसंद",
    "hero_subtitle": "InnSync एकमात्र PMS है जिसमें रियल-टाइम IoT वेरिफिकेशन है—अब कोई भी रुपया रिकॉर्ड से बाहर नहीं जाएगा।",
    "hero_trust": "भारत के 20+ होटलों द्वारा भरोसेमंद",
    "hero_pill1": "100% डेटा पारदर्शिता",
    "hero_pill2": "तुरंत अलर्ट",
    "hero_pill3": "अब नहीं होगा Revenue Leak",
    // Live Control
    "live_title": "लाइव कंट्रोल पैनल",
    "live_status_demo": "डेमो",
    "live_kpi_occupancy": "ऑक्युपेंसी",
    "live_kpi_registered": "रजिस्टर्ड",
    "live_kpi_leakage": "लीकेज",
    "live_alert_title": "लीक अलर्ट: 2 कमरे भरे हैं पर बुकिंग नहीं",
    "live_alert_desc": "IoT सेंसर ने रूम 204, 311 फ्लैग किया • कार्रवाई करें",
    "live_bullets": [
      "IoT सेंसर अनरिकॉर्डेड बुकिंग पकड़ते हैं",
      "सभी प्रमुख OTA प्लेटफ़ॉर्म्स के साथ इंटीग्रेशन",
      "मालिक व मैनेजर के लिए सहज डैशबोर्ड"
    ],
    // Problem
    "problem_title": "समस्या",
    "problem_text": "कमरे भरे, रेकॉर्ड खाली। वॉक-इन बिना निशान। मैनुअल अपडेट होते ही नहीं—बिना विज़िबिलिटी के 10%+ राजस्व गायब।",
    "problem_point1": "कमरे occupied लेकिन रिकॉर्ड में नहीं",
    "problem_point2": "अनट्रैक्ड वॉक-इन और स्टाफ की गलतियाँ",
    "problem_point3": "डैशबोर्ड हकीकत से मेल नहीं खाते",
    "risk_title": "मासिक जोखिम स्नैपशॉट",
    "risk_label1": "Unrecorded Nights",
    "risk_label2": "Monthly Loss",
    "risk_label3": "Occupancy Gap",
    // Solution & pricing
    "solution_title": "InnSync लीकेज कैसे रोकता है",
    "solution_tagline": "हर बुकिंग का हिसाब। रियल-टाइम कंट्रोल। सहज संचालन।",
    "sol_card1_title": "IoT ऑक्युपेंसी सेंसर",
    "sol_card1_desc": "अनरजिस्टर्ड स्टे तुरंत पकड़ें—बिना कैमरा, बिना PII। कमरा use हुआ तो पता चलेगा।",
    "sol_card2_title": "सभी OTA इंटीग्रेशन",
    "sol_card2_desc": "OYO, Booking.com, MakeMyTrip, Agoda, Airbnb व अन्य के साथ सिंक—कोई मैनुअल एंट्री नहीं।",
    "sol_card3_title": "इंट्यूटिव डैशबोर्ड",
    "sol_card3_desc": "ओनर्स व मैनेजर्स के लिए लाइव occupancy, revenue और discrepancies।",
    "pricing_title": "प्राइसिंग",
    "pricing_headline": "सिर्फ ₹150/माह में 10%+ राजस्व वृद्धि",
    "pricing_sub": "सिंपल और पारदर्शी—कोई छिपा शुल्क नहीं।",
    "pricing_tag1": "कोई लंबा कॉन्ट्रैक्ट नहीं",
    "pricing_tag2": "आसान इंस्टॉल",
    "pricing_tag3": "24×7 सपोर्ट",
    "call_now_btn": "अभी कॉल करें",
    "pricing_demo_btn": "फ्री डेमो बुक करें",
    // Trust & features
    "trust_title": "ट्रस्ट के लिए बना। रिज़ल्ट के लिए डिज़ाइन।",
    "trust_subtitle": "सिक्योरिटी, एकाउंटेबिलिटी और अपटाइम—होटल के भरोसे के लिए तैयार।",
    "trust_item1_title": "एंड‑टू‑एंड एन्क्रिप्शन",
    "trust_item1_desc": "ट्रांज़िट और रेस्ट—दोनों में",
    "trust_item2_title": "ओनर‑फर्स्ट विज़िबिलिटी",
    "trust_item2_desc": "हर कमरा, हर दिन",
    "trust_item3_title": "99.9% अपटाइम",
    "trust_item3_desc": "24×7 मॉनिटरिंग",
    "trust_item4_title": "ऑडिट लॉग्स",
    "trust_item4_desc": "हर बदलाव का पूरा रिकॉर्ड",
    "ft_trio1_title": "60 सेकंड में लीक अलर्ट",
    "ft_trio1_desc": "सेंसर से फोन तक",
    "ft_trio2_title": "100% ऑडिट ट्रेल",
    "ft_trio2_desc": "हर बदलाव दर्ज",
    "ft_trio3_title": "ऑटो‑रिकॉन्सिलिएशन",
    "ft_trio3_desc": "दैनिक OTA क्रॉस‑चेक",
    // Trusted by
    "trusted_title": "Trusted By",
    "trusted_subtitle": "प्रमुख हॉस्पिटैलिटी ब्रांड InnSync पर भरोसा करते हैं",
    // Demo
    "demo_title": "फ्री डेमो बुक करें",
    "demo_subtitle": "अपनी प्रॉपर्टी के बारे में बताएं—हम दिखाएंगे कैसे InnSync खुद का खर्च निकालता है।",
    "demo_name_label": "आपका नाम",
    "demo_phone_label": "फ़ोन",
    "demo_hotel_label": "होटल / प्रॉपर्टी नाम",
    "demo_submit_label": "डेमो रिक्वेस्ट करें",
    "demo_or_call_text": "या हमें सीधे कॉल करें",
    "demo_success": "धन्यवाद! हम डेमो शेड्यूल करने के लिए आपसे संपर्क करेंगे।",
    "how_timeline": [
      {"title": "कनेक्ट करें", "desc": "कुछ ही मिनटों में InnSync से होटल जोड़ें—कोई तकनीकी ज्ञान जरूरी नहीं।", "icon": "🔗"},
      {"title": "डिटेक्ट करें", "desc": "IoT सेंसर असली उपस्थिति पकड़ते हैं और डैशबोर्ड पर भेजते हैं।", "icon": "📡"},
      {"title": "सत्यापित करें", "desc": "हमारा एल्गोरिदम बुकिंग और उपस्थिति का मिलान कर गड़बड़ी को फ़्लैग करता है।", "icon": "🤖"},
      {"title": "अलर्ट पाएं", "desc": "अनरिकॉर्डेड स्टे या संदिग्ध गतिविधि पर तुरंत अलर्ट पाएं।", "icon": "⚡"}
    ],
    "testimonial_heading": "हमारे ग्राहक क्या कहते हैं",
    "testimonials": [
      {"quote": "InnSync के साथ मुझे अपनी प्रॉपर्टी की पूरी तस्वीर दिखती है—अब कोई ब्लाइंड स्पॉट नहीं।", "cite": "रोहित शर्मा, होटल मालिक, बेंगलुरु"},
      {"quote": "अब कोई राजस्व लीकेज नहीं। अलर्ट्स शानदार हैं!", "cite": "प्रिया देसाई, ब्लू लैगून"},
      {"quote": "सेटअप बहुत आसान था, अब होटल की कमाई पर पूरा नियंत्रण है।", "cite": "अमित वर्मा, अर्बन नेस्ट"},
      {"quote": "IoT वेरिफिकेशन से ऑक्युपेंसी पर विवाद खत्म हो गए।", "cite": "सीमा कपूर, रॉयल स्टे"},
      {"quote": "अलर्ट्स से टीम तुरंत कार्रवाई करती है—अब मैनुअल पीछा नहीं।", "cite": "विक्रम राव, फ्रंट ऑफिस मैनेजर"},
      {"quote": "पहले ही हफ्ते में छूटा हुआ राजस्व वापस मिला।", "cite": "नेहा गुप्ता, मालिक, पुणे"},
      {"quote": "हमारे मौजूदा PMS के साथ इंटीग्रेशन बिना परेशानी के हुआ।", "cite": "करण मेहता, जीएम, बीचसाइड इन"},
      {"quote": "डैशबोर्ड सरल है और जरूरी चीजें दिखाता है।", "cite": "अनिता अय्यर, बुटीक होटल"},
      {"quote": "InnSync अपनी कीमत वसूल कर देता है—लीकेज रुक गए।", "cite": "राहुल जैन, मल्टी-प्रॉपर्टी मालिक"}
    ],
    "login_title": "डेमो लॉगिन करें",
    "login_subtitle": "सैंपल क्रेडेंशियल्स का उपयोग करें:",
    "login_email_label": "ईमेल",
    "login_password_label": "पासवर्ड",
    "login_owner_btn": "मालिक के रूप में लॉगिन करें",
    "login_manager_btn": "मैनेजर के रूप में लॉगिन करें",
  "login_terms": "लॉगिन करके आप डेमो शर्तों से सहमत हैं। डेटा केवल डेमो के लिए है।",
  "feature1_title": "IoT-संचालित रूम मॉनिटरिंग",
  "feature1_desc": "स्मार्ट सेंसर असली उपस्थिति ट्रैक करते हैं, सिर्फ बुकिंग नहीं।",
  "feature2_title": "तत्काल राजस्व अलर्ट",
  "feature2_desc": "जैसे ही गड़बड़ी या लीकेज मिले, तुरंत सूचना पाएं।",
  "feature3_title": "मालिक-प्रथम डैशबोर्ड",
  "feature3_desc": "लाइव ऑक्युपेंसी, बुकिंग और रेवेन्यू एक ही जगह देखें।",
  "usecase1_title": "हर वॉक-इन पकड़ें",
  "usecase1_desc": "अब कोई अनरिकॉर्डेड स्टे नहीं—हर मेहमान ऑटोमैटिक ट्रैक होता है।",
  "usecase2_title": "मालिक का नियंत्रण",
  "usecase2_desc": "मालिक को तुरंत अलर्ट और पूरी विज़िबिलिटी, कहीं से भी।",
  "usecase3_title": "आसान इंटीग्रेशन",
  "usecase3_desc": "आपके मौजूदा PMS और बुकिंग प्लेटफ़ॉर्म के साथ काम करता है।",
  "faq_heading": "अक्सर पूछे जाने वाले सवाल",
  "faq_q1": "InnSync राजस्व लीकेज कैसे रोकता है?",
  "faq_a1": "InnSync IoT सेंसर और स्मार्ट एल्गोरिदम से असली ऑक्युपेंसी और बुकिंग का मिलान करता है, और तुरंत गड़बड़ी को फ़्लैग करता है।",
  "faq_q2": "क्या InnSync लगाना आसान है?",
  "faq_a2": "हाँ! ज़्यादातर होटल 30 मिनट में चालू हो जाते हैं। कोई तकनीकी ज्ञान जरूरी नहीं।",
  "faq_q3": "क्या InnSync मेरे PMS के साथ काम करेगा?",
  "faq_a3": "InnSync मुख्य PMS और बुकिंग प्लेटफ़ॉर्म के साथ इंटीग्रेट होता है। अधिक जानकारी के लिए संपर्क करें।",
  "feedback_heading": "अपना फीडबैक साझा करें",
  "feedback_label": "आपका फीडबैक हमें बेहतर बनाता है:",
  "feedback_placeholder": "अपने सुझाव, विचार या सवाल यहाँ लिखें...",
  "feedback_submit": "फीडबैक भेजें",
  "feedback_success": "आपके फीडबैक के लिए धन्यवाद!"
  ,
  "demo_heading": "लाइव डेमो बुक करें",
  "demo_subtitle": "कुछ विवरण साझा करें, हम डेमो शेड्यूल करने के लिए संपर्क करेंगे।",
  "demo_name_label": "आपका नाम",
  "demo_name_placeholder": "रोहित शर्मा",
  "demo_hotel_label": "होटल/प्रॉपर्टी का नाम",
  "demo_hotel_placeholder": "Sunrise Residency",
  "demo_email_label": "कार्य ईमेल",
  "demo_email_placeholder": "you@example.com",
  "demo_phone_label": "फोन",
  "demo_phone_placeholder": "+91 98765 43210",
  "demo_city_label": "शहर (वैकल्पिक)",
  "demo_city_placeholder": "बेंगलुरु",
  "demo_cancel": "रद्द करें",
  "demo_submit": "सबमिट",
  "demo_error_name": "कृपया वैध नाम दर्ज करें",
  "demo_error_hotel": "कृपया वैध होटल नाम दर्ज करें",
  "demo_error_email": "कृपया वैध ईमेल दर्ज करें",
  "demo_error_phone": "कृपया वैध फ़ोन नंबर दर्ज करें",
  "demo_success_title": "अनुरोध प्राप्त हुआ",
  "demo_success_body": "धन्यवाद! हम जल्द ही आपसे संपर्क करेंगे।",
  "demo_call_title": "बात करना पसंद है?",
  "demo_call_hours": "सभी दिन, सुबह 9 बजे – शाम 5 बजे कॉल करें",
  "demo_call_number_label": "कॉल करें {number}"
  },
  "kn": {
  // Navbar & common
  "nav_problem": "ಸಮಸ್ಯೆ",
  "nav_solution": "ಪರಿಹಾರ",
  "nav_trusted": "ವಿಶ್ವಾಸ",
  "nav_demo": "ಡೆಮೊ",
  "nav_faq": "ಪ್ರಶ್ನೋತ್ತರ",
  "nav_about": "About",
  "nav_login": "ಲಾಗಿನ್",
  "nav_live_control": "Live Control",
  "lang_popup_title": "ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ",
    "hero_title": "ಆದಾಯ ಸೋರಿಕೆ ನಿಲ್ಲಿಸಿ. ಪ್ರತಿಯೊಂದು ರೂಪಾಯಿಯನ್ನೂ ಸೆರೆಹಿಡಿಯಿರಿ.",
    "cta_call_label": "ಉಚಿತ ಪರೀಕ್ಷೆಗೆ ಈಗಲೇ ಕರೆ ಮಾಡಿ",
    "cta_call_number": "+91 98765 43210",
    "cta_demo_label": "ಲೈವ್ ಡೆಮೊ ಬುಕ್ ಮಾಡಿ",
    "problem_heading": "ನಿಮಗೆ ಗೊತ್ತಿಲ್ಲದೆ ಹಣ ಕಳೆದುಕೊಳ್ಳುತ್ತಿದ್ದೀರಾ?",
    "problem_points": [
      "ರಿಸೆಪ್ಷನ್ ನಗದು ಪಡೆಯುತ್ತದೆ, PMS ನಲ್ಲಿ ದಾಖಲಿಲ್ಲ",
      "ಕೊಠಡಿ ಬಳಸಲಾಗುತ್ತಿದೆ, ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ‘Vacant’ ಎಂದು ತೋರಿಸುತ್ತದೆ",
      "ಮಾಲೀಕರ ಆದಾಯ ನಿಶ್ಶಬ್ದವಾಗಿ ಕಳೆದುಹೋಗುತ್ತದೆ"
    ],
    "solution_heading": "InnSync ಇದಕ್ಕೆ ಪರಿಹಾರ ಹೇಗೆ ಕೊಡುತ್ತದೆ",
    "solution_points": [
      "ಪ್ರತಿ ಕೊಠಡಿಯಲ್ಲಿ ಮಾನವ ಹಾಜರಾತಿ ಪತ್ತೆ ಮಾಡುವ IoT ಸೆನ್ಸರ್‌ಗಳು",
      "ಡೇಟಾ ನೈಜ-ಕಾಲದಲ್ಲಿ PMS ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಬರುತ್ತದೆ",
      "ಅಲ್ಗಾರಿದಮ್ ಆಕ್ಯುಪೆನ್ಸಿ vs ಬುಕ್ಕಿಂಗ್ ಹೋಲಿಕೆ ಮಾಡಿ ತಕ್ಷಣ ಫ್ಲ್ಯಾಗ್ ಮಾಡುತ್ತದೆ"
    ],
    "benefits_heading": "ಹೋಟೆಲ್ ಮಾಲೀಕರು InnSync ಯಾಕೆ ಆಯ್ಕೆ ಮಾಡುತ್ತಾರೆ",
    "benefits_points": [
      "ಪೂರ್ಣ ಗೋಚರತೆ: ಲೈವ್ ಆಕ್ಯುಪೆನ್ಸಿ, ಬುಕ್ಕಿಂಗ್ ಮತ್ತು ಆದಾಯ",
      "ದಾಖಲಾಗದ ವಾಸ್ತವ್ಯಗಳಿಗೆ ತಕ್ಷಣ ಎಚ್ಚರಿಕೆ",
      "ನಗದು ಮತ್ತು ವಾಕ್-ಇನ್‌ಗಳಲ್ಲಿ ಸೋರಿಕೆ ನಿಲ್ಲಿಸಿ",
      "ಮುಖ್ಯ ಬುಕ್ಕಿಂಗ್ ವೇದಿಕೆಗಳೊಂದಿಗೆ ಕೆಲಸ"
    ],
    "how_heading": "ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    "how_steps": [
      "OTAs ಮತ್ತು ಡೈರೆಕ್ಟ್ ಚಾನಲ್‌ಗಳಿಂದ ಬುಕ್ಕಿಂಗ್‌ಗಳು ಬರುತ್ತವೆ",
      "ಸೆನ್ಸರ್‌ಗಳು ನೈಜ-ಕಾಲದಲ್ಲಿ ಆಕ್ಯುಪೆನ್ಸಿ ಪತ್ತೆಹಿಡಿಯುತ್ತವೆ",
      "ಸಿಸ್ಟಂ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಡೇಟಾ ಹೋಲಿಕೆ ಮಾಡುತ್ತದೆ",
      "ಗೊಂದಲ ಕಂಡರೆ ಮಾಲೀಕರಿಗೆ ತಕ್ಷಣ ಅಲರ್ಟ್"
    ],
    "testimonial_heading": "ಮುಖ್ಯ ಹೋಟೆಲ್‌ಗಳಲ್ಲಿ ಪೈಲಟ್‌ನಲ್ಲಿ",
    "testimonial_quote": "InnSync ಜೊತೆ ನನ್ನ ಪ್ರಾಪರ್ಟಿಯಲ್ಲಿ ಏನು ನಡೆಯುತ್ತಿದೆ ಎಂಬುದು ಸ್ಪಷ್ಟ—ಇನ್ನು ಯಾವುದೇ ಬ್ಲೈಂಡ್ ಸ್ಪಾಟ್ ಇಲ್ಲ.",
    "testimonial_cite": "ರೋಹಿತ್ ಶರ್ಮಾ, ಹೋಟೆಲ್ ಮಾಲೀಕ, ಬೆಂಗಳೂರು",
    "cta_repeat_heading": "InnSync ಅನ್ನು ಲೈವ್ ನೋಡಲು ಸಿದ್ಧವೇ?",
    "cta_repeat_body": "ಈಗಲೇ ಕರೆ ಮಾಡಿ—ಉಚಿತ ಪರೀಕ್ಷೆ ಪಡೆದು, ಎಷ್ಟು ಉಳಿತಾಯ ಸಾಧ್ಯ ನೋಡಿರಿ.",
    "footer_tagline": "InnSync – ಪ್ರತಿಯೊಂದು ರೂಪಾಯಿ, ಪ್ರತಿಯೊಂದು ಕೊಠಡಿ, ಪ್ರತಿದಿನ ಸುರಕ್ಷಿತ.",
    "lang_label": "ಭಾಷೆ"
    ,
    "hero_badge": "🏨 ಸ್ಮಾರ್ಟ್ ಹೋಟೆಲ್‌ಗಳ ಆಯ್ಕೆ",
    "hero_subtitle": "InnSync ಮಾತ್ರ PMS—ನೈಜಕಾಲ IoT ಪರಿಶೀಲನೆ. ಯಾವುದೇ ರೂಪಾಯಿ ಕೈ ತಪ್ಪದು.",
    "hero_trust": "ಭಾರತದ 20+ ಹೋಟೆಲ್‌ಗಳ ವಿಶ್ವಾಸ",
    "hero_pill1": "100% ಡೇಟಾ ಪಾರದರ್ಶಕತೆ",
    "hero_pill2": "ತಕ್ಷಣದ ಎಚ್ಚರಿಕೆ",
    "hero_pill3": "ಇನ್ನು ಆದಾಯ ಸೋರಿಕೆ ಇಲ್ಲ",
    // Live Control
    "live_title": "ಲೈವ್ ಕಂಟ್ರೋಲ್ ಪ್ಯಾನೆಲ್",
    "live_status_demo": "ಡೆಮೊ",
    "live_kpi_occupancy": "ಆಕ್ಯುಪೆನ್ಸಿ",
    "live_kpi_registered": "ನೋಂದಾಯಿತ",
    "live_kpi_leakage": "ಲೀಕೆಜ್",
    "live_alert_title": "ಲೀಕ್ ಎಚ್ಚರಿಕೆ: 2 ಕೊಠಡಿ ತುಂಬಿವೆ, ಬುಕ್ಕಿಂಗ್ ಇಲ್ಲ",
    "live_alert_desc": "IoT ಸೆನ್ಸರ್: ಕೊಠಡಿ 204, 311 • ಕ್ರಮ ಅಗತ್ಯ",
    "live_bullets": [
      "IoT ಸೆನ್ಸರ್‌ಗಳು ನೋಂದಾಯಿಸದ ಬುಕ್ಕಿಂಗ್ ಪತ್ತೆಹಿಡಿಯುತ್ತವೆ",
      "ಎಲ್ಲಾ ಪ್ರಮುಖ OTAಗಳೊಂದಿಗೆ ಇಂಟಿಗ್ರೇಶನ್",
      "ಮಾಲೀಕ/ಮ್ಯಾನೇಜರ್‌ಗಳಿಗೆ ಸುಲಭ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್"
    ],
    // Problem
    "problem_title": "ಸಮಸ್ಯೆ",
    "problem_text": "ಕೊಠಡಿಗಳು ತುಂಬಿ, ದಾಖಲೆಗಳು ಖಾಲಿ. ವಾಕ್-ಇನ್‌ಗಳಿಗೆ ದಾಖಲೆ ಇಲ್ಲ. ನೈಜ ಗೋಚರತೆ ಇಲ್ಲದಿದ್ದರೆ 10%+ ಆದಾಯ ಕಳೆದುಹೋಗುತ್ತದೆ.",
    "problem_point1": "ಬಳಕೆಯಲ್ಲಿದರೂ ದಾಖಲಾಗದ ಕೊಠಡಿಗಳು",
    "problem_point2": "ದಾಖಲಾಗದ ವಾಕ್-ಇನ್‌ಗಳು ಮತ್ತು ಸಿಬ್ಬಂದಿ ದೋಷಗಳು",
    "problem_point3": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ವಾಸ್ತವಿಕತೆಗೆ ಹೊಂದಿಕೆಯಾಗದು",
    "risk_title": "ಮಾಸಿಕ ಅಪಾಯ ನೆನಪು",
    "risk_label1": "Unrecorded Nights",
    "risk_label2": "Monthly Loss",
    "risk_label3": "Occupancy Gap",
    // Solution & pricing
    "solution_title": "InnSync ಲೀಕೆಜ್ ಹೇಗೆ ನಿಲ್ಲಿಸುತ್ತದೆ",
    "solution_tagline": "ಪ್ರತಿ ಬುಕ್ಕಿಂಗ್ ಲೆಕ್ಕ. ನೈಜ-ಕಾಲ ನಿಯಂತ್ರಣ. ಸುಗಮ ಕಾರ್ಯಾಚರಣೆ.",
    "sol_card1_title": "IoT ಆಕ್ಯುಪೆನ್ಸಿ ಸೆನ್ಸರ್‌ಗಳು",
    "sol_card1_desc": "ಅನ್ರಿಕಾರ್ಡ್ ವಾಸ್ತವ್ಯ ತಕ್ಷಣ ಪತ್ತೆ—ಕ್ಯಾಮೆರಾ/PII ಇಲ್ಲ.",
    "sol_card2_title": "ಎಲ್ಲಾ OTA ಇಂಟಿಗ್ರೇಶನ್",
    "sol_card2_desc": "OYO, Booking.com, MMT, Agoda, Airbnb ಇತ್ಯಾದಿಗಳೊಂದಿಗೆ ಸಿಂಕ್.",
    "sol_card3_title": "ಸರಳ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "sol_card3_desc": "ಮಾಲೀಕ/ಮ್ಯಾನೇಜರ್‌ಗಳಿಗೆ ಲೈವ್ ಮೀಟ್ರಿಕ್‌ಗಳು.",
    "pricing_title": "ಬೆಲೆ",
    "pricing_headline": "ಮಾತ್ರ ₹150/ತಿಂಗಳಿಗೆ 10%+ ಆದಾಯ ಹೆಚ್ಚಳ",
    "pricing_sub": "ಸರಳ, ಪಾರದರ್ಶಕ—ಗೊಬ್ಬರ ಶುಲ್ಕ ಇಲ್ಲ",
    "pricing_tag1": "ದಿರ್ಘಾವಧಿ ಒಪ್ಪಂದ ಬೇಕಿಲ್ಲ",
    "pricing_tag2": "ಸರಳ ಇನ್‌ಸ್ಟಾಲ್",
    "pricing_tag3": "24×7 ಬೆಂಬಲ",
    "call_now_btn": "ಈಗ ಕರೆ ಮಾಡಿ",
    "pricing_demo_btn": "ಫ್ರೀ ಡೆಮೊ ಬುಕ್ ಮಾಡಿ",
    // Trust & features
    "trust_title": "ವಿಶ್ವಾಸಕ್ಕೆ ವಿನ್ಯಾಸ. ಫಲಿತಾಂಶಗಳಿಗೆ ರೂಪಿಸಲಾಗಿದೆ.",
    "trust_subtitle": "ಭದ್ರತೆ, ಹೊಣೆಗಾರಿಕೆ ಮತ್ತು ಅಪ್‌ಟೈಮ್—ಹೋಟೆಲ್‌ಗಳಿಗೆ ನಂಬಿಕೆ.",
    "trust_item1_title": "ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್ಕ್ರಿಪ್ಷನ್",
    "trust_item1_desc": "ಟ್ರಾನ್ಸಿಟ್ ಮತ್ತು ರೆಸ್ಟ್",
    "trust_item2_title": "ಮಾಲೀಕ-ಪ್ರಥಮ ಗೋಚರತೆ",
    "trust_item2_desc": "ಪ್ರತಿ ಕೊಠಡಿ, ಪ್ರತಿದಿನ",
    "trust_item3_title": "99.9% ಅಪ್‌ಟೈಮ್",
    "trust_item3_desc": "24×7 ಮೇಲೆ ನಿಗಾವಳಿ",
    "trust_item4_title": "ಆಡಿಟ್ ಲಾಗ್‌ಗಳು",
    "trust_item4_desc": "ಪೂರ್ಣ ಬದಲಾವಣೆಯ ದಾಖಲೆ",
    "ft_trio1_title": "60 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಲೀಕ್ ಎಚ್ಚರಿಕೆ",
    "ft_trio1_desc": "ಸೆನ್ಸರ್‌ನಿಂದ ಫೋನ್‌ಗೆ",
    "ft_trio2_title": "100% ಆಡಿಟ್ ಟ್ರೇಲ್",
    "ft_trio2_desc": "ಪ್ರತಿ ಬದಲಾವಣೆ ದಾಖಲೆ",
    "ft_trio3_title": "ಸ್ವಯಂ-ಮೇಳಸಮಾಯೋಜನೆ",
    "ft_trio3_desc": "ಪ್ರತಿದಿನ OTA ಕ್ರಾಸ್-ಚೆಕ್",
    // Trusted
    "trusted_title": "Trusted By",
    "trusted_subtitle": "ಮುಖ್ಯ ಅತಿಥಿ ವಸತಿ ಬ್ರ್ಯಾಂಡ್‌ಗಳು InnSync ನಂಬುತ್ತವೆ",
    // Demo
    "demo_title": "ಉಚಿತ ಡೆಮೊ ಬುಕ್ ಮಾಡಿ",
    "demo_subtitle": "ನಿಮ್ಮ ಪ್ರಾಪರ್ಟಿ ವಿವರ ನೀಡಿ—InnSync ಹೇಗೆ ಲಾಭ ಕೊಡುತ್ತದೆ ನೋಡಿ.",
    "demo_name_label": "ನಿಮ್ಮ ಹೆಸರು",
    "demo_phone_label": "ಫೋನ್",
    "demo_hotel_label": "ಹೋಟೆಲ್ / ಪ್ರಾಪರ್ಟಿ ಹೆಸರು",
    "demo_submit_label": "ಡೆಮೊ ವಿನಂತಿಸಿ",
    "demo_or_call_text": "ಅಥವಾ ಕರೆ ಮಾಡಿ",
    "demo_success": "ಧನ್ಯವಾದಗಳು! ಡೆಮೊ ನಿಗದಿ ಮಾಡಲು ನಾವು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.",
    "how_timeline": [
      {"title": "ಕನೆಕ್ಟ್ ಮಾಡಿ", "desc": "ನಿಮ್ಮ ಹೋಟೆಲ್ ಅನ್ನು InnSync ಗೆ ನಿಮಿಷಗಳಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ—ಯಾವುದೇ ತಾಂತ್ರಿಕ ಜ್ಞಾನ ಬೇಡ.", "icon": "🔗"},
      {"title": "ಪತ್ತೆಹಚ್ಚಿ", "desc": "IoT ಸೆನ್ಸರ್‌ಗಳು ನೈಜ ಹಾಜರಾತಿಯನ್ನು ಪತ್ತೆಹಿಡಿದು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಕಳುಹಿಸುತ್ತವೆ.", "icon": "📡"},
      {"title": "ಪರಿಶೀಲಿಸಿ", "desc": "ನಮ್ಮ ಅಲ್ಗಾರಿದಮ್ ಬುಕ್ಕಿಂಗ್ ಮತ್ತು ಹಾಜರಾತಿಯನ್ನು ಹೋಲಿಸಿ ಗೊಂದಲವನ್ನು ಫ್ಲ್ಯಾಗ್ ಮಾಡುತ್ತದೆ.", "icon": "🤖"},
      {"title": "ಎಚ್ಚರಿಕೆ", "desc": "ದಾಖಲಾಗದ ವಾಸ್ತವ್ಯ ಅಥವಾ ಅನುಮಾನಾಸ್ಪದ ಚಟುವಟಿಕೆಗೆ ತಕ್ಷಣ ಎಚ್ಚರಿಕೆ ಸಿಗುತ್ತದೆ.", "icon": "⚡"}
    ],
    "testimonial_heading": "ನಮ್ಮ ಗ್ರಾಹಕರು ಹೇಳುವುದು",
    "testimonials": [
      {"quote": "InnSync ಜೊತೆ ನನ್ನ ಪ್ರಾಪರ್ಟಿಯಲ್ಲಿ ಏನು ನಡೆಯುತ್ತಿದೆ ಎಂಬುದು ಸ್ಪಷ್ಟ—ಇನ್ನು ಯಾವುದೇ ಬ್ಲೈಂಡ್ ಸ್ಪಾಟ್ ಇಲ್ಲ.", "cite": "ರೋಹಿತ್ ಶರ್ಮಾ, ಹೋಟೆಲ್ ಮಾಲೀಕ, ಬೆಂಗಳೂರು"},
      {"quote": "ಆದಾಯ ಸೋರಿಕೆ ಶೂನ್ಯವಾಗಿದೆ. ಎಚ್ಚರಿಕೆಗಳು ಅದ್ಭುತ!", "cite": "ಪ್ರಿಯಾ ದೇಸಾಯಿ, ಬ್ಲೂ ಲ್ಯಾಗೂನ್"},
      {"quote": "ಸೆಟಪ್ ತುಂಬಾ ಸುಲಭ, ಈಗ ಆದಾಯದ ಮೇಲೆ ಸಂಪೂರ್ಣ ನಿಯಂತ್ರಣ ಇದೆ.", "cite": "ಅಮಿತ್ ವರ್ಮಾ, ಅರ್ಬನ್ ನೆಸ್ಟ್"},
      {"quote": "IoT ಪರಿಶೀಲನೆಯಿಂದ ಆಕ್ಯುಪೆನ್ಸಿ ಬಗ್ಗೆ ಇರುವ ವಿವಾದಗಳು ಅಂತ್ಯವಾದವು.", "cite": "ಸೀಮಾ ಕಪೂರ್, ರಾಯಲ್ ಸ್ಟೇ"},
      {"quote": "ಎಚ್ಚರಿಕೆಗಳಿಂದ ತಂಡ ತಕ್ಷಣ ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ—ಇನ್ನು ಕೈಯಿಂದ ಹಿಂಬಾಲಿಕೆ ಬೇಡ.", "cite": "ವಿಕ್ರಮ್ ರಾವ್, ಫ್ರಂಟ್ ಆಫೀಸ್ ಮ್ಯಾನೇಜರ್"},
      {"quote": "ಮೊದಲ ವಾರದಲ್ಲೇ ತಪ್ಪಿದ ಆದಾಯ ವಶಕ್ಕೆ ಬಂದಿದೆ.", "cite": "ನೇಹಾ ಗುಪ್ತ, ಮಾಲಕಿ, ಪುಣೆ"},
      {"quote": "ನಮ್ಮ PMS ಜೊತೆಗೆ ಇಂಟಿಗ್ರೇಶನ್ ಸುಲಭವಾಗಿ ಆಯಿತು.", "cite": "ಕರಣ್ ಮೇಹತಾ, ಜಿಎಂ, ಬೀಚ್‌ಸೈಡ್ ಇನ್"},
      {"quote": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಸರಳವಾಗಿದೆ ಮತ್ತು ಮುಖ್ಯ ವಿಷಯಗಳನ್ನು ತೋರಿಸುತ್ತದೆ.", "cite": "ಅನಿತಾ ಅಯ್ಯರ್, ಬೌಟಿಕ್ ಹೋಟೆಲ್"},
      {"quote": "InnSync ಖರ್ಚಿನಷ್ಟು ಮೌಲ್ಯ ಕೊಡುತ್ತದೆ—ಸೋರಿಕೆ ನಿಂತಿದೆ.", "cite": "ರಾಹುಲ್ ಜೈನ್, ಬಹು-ಪ್ರಾಪರ್ಟಿ ಮಾಲೀಕ"}
    ],
    "login_title": "ಡೆಮೊಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
    "login_subtitle": "ಉದಾಹರಣೆಯ ಕ್ರೆಡೆನ್ಶಿಯಲ್ ಬಳಸಿ:",
    "login_email_label": "ಇಮೇಲ್",
    "login_password_label": "ಪಾಸ್ವರ್ಡ್",
    "login_owner_btn": "ಮಾಲೀಕರಾಗಿ ಲಾಗಿನ್ ಮಾಡಿ",
    "login_manager_btn": "ಮ್ಯಾನೇಜರ್ ಆಗಿ ಲಾಗಿನ್ ಮಾಡಿ",
  "login_terms": "ಲಾಗಿನ್ ಮಾಡಿದರೆ ನೀವು ಡೆಮೊ ನಿಯಮಗಳಿಗೆ ಒಪ್ಪಿಗೆ ನೀಡಿದ್ದೀರಿ. ಡೇಟಾ ಮಾದರಿ ಮಾತ್ರ.",
  "feature1_title": "IoT ಚಾಲಿತ ಕೊಠಡಿ ನಿಗಾವಳಿ",
  "feature1_desc": "ಸ್ಮಾರ್ಟ್ ಸೆನ್ಸರ್ ಗಳು ನೈಜ ಹಾಜರಾತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡುತ್ತವೆ, ಬುಕ್ಕಿಂಗ್ ಅಲ್ಲ.",
  "feature2_title": "ತಕ್ಷಣ ಆದಾಯ ಎಚ್ಚರಿಕೆ",
  "feature2_desc": "ಗೊಂದಲ ಅಥವಾ ಸೋರಿಕೆ ಕಂಡುಬಂದ ತಕ್ಷಣ ನೋಟಿಫಿಕೇಶನ್ ಸಿಗುತ್ತದೆ.",
  "feature3_title": "ಮಾಲೀಕರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  "feature3_desc": "ಲೈವ್ ಆಕ್ಯುಪೆನ್ಸಿ, ಬುಕ್ಕಿಂಗ್ ಮತ್ತು ಆದಾಯವನ್ನು ಒಂದೇ ಕಡೆ ನೋಡಿ.",
  "usecase1_title": "ಪ್ರತಿ ವಾಕ್-ಇನ್ ಹಿಡಿಯಿರಿ",
  "usecase1_desc": "ಇನ್ನು ಅನ್ರಿಕಾರ್ಡ್ ವಾಸ್ತವ್ಯ ಇಲ್ಲ—ಪ್ರತಿ ಅತಿಥಿ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಟ್ರ್ಯಾಕ್ ಆಗುತ್ತಾನೆ.",
  "usecase2_title": "ಮಾಲೀಕರ ನಿಯಂತ್ರಣ",
  "usecase2_desc": "ಮಾಲೀಕರಿಗೆ ತಕ್ಷಣ ಎಚ್ಚರಿಕೆ ಮತ್ತು ಪೂರ್ಣ ಗೋಚರತೆ, ದೂರದಿಂದಲೂ.",
  "usecase3_title": "ಸುಲಭ ಇಂಟಿಗ್ರೇಶನ್",
  "usecase3_desc": "ನಿಮ್ಮ PMS ಮತ್ತು ಬುಕ್ಕಿಂಗ್ ವೇದಿಕೆಗಳೊಂದಿಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
  "faq_heading": "ಪದೇಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
  "faq_q1": "InnSync ಆದಾಯ ಸೋರಿಕೆ ಹೇಗೆ ತಡೆಯುತ್ತದೆ?",
  "faq_a1": "InnSync IoT ಸೆನ್ಸರ್ ಮತ್ತು ಸ್ಮಾರ್ಟ್ ಅಲ್ಗಾರಿದಮ್ ಬಳಸಿ ನೈಜ ಹಾಜರಾತಿ ಮತ್ತು ಬುಕ್ಕಿಂಗ್ ಹೋಲಿಕೆ ಮಾಡಿ ತಕ್ಷಣ ಗೊಂದಲವನ್ನು ಫ್ಲ್ಯಾಗ್ ಮಾಡುತ್ತದೆ.",
  "faq_q2": "InnSync ಹೋಟೆಲ್‌ನಲ್ಲಿ ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡುವುದು ಸುಲಭವೇ?",
  "faq_a2": "ಹೌದು! ಹೆಚ್ಚಿನ ಹೋಟೆಲ್‌ಗಳು 30 ನಿಮಿಷಗಳಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ. ಯಾವುದೇ ತಾಂತ್ರಿಕ ಜ್ಞಾನ ಬೇಡ.",
  "faq_q3": "InnSync ನನ್ನ PMS ಜೊತೆಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆಯೇ?",
  "faq_a3": "InnSync ಪ್ರಮುಖ PMS ಮತ್ತು ಬುಕ್ಕಿಂಗ್ ವೇದಿಕೆಗಳೊಂದಿಗೆ ಇಂಟಿಗ್ರೇಟ್ ಆಗುತ್ತದೆ. ವಿವರಗಳಿಗೆ ಸಂಪರ್ಕಿಸಿ.",
  "feedback_heading": "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ಹಂಚಿಕೊಳ್ಳಿ",
  "feedback_label": "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ನಮಗೆ ಉತ್ತಮವಾಗಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ:",
  "feedback_placeholder": "ನಿಮ್ಮ ಸಲಹೆ, ಅಭಿಪ್ರಾಯ ಅಥವಾ ಪ್ರಶ್ನೆಗಳನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...",
  "feedback_submit": "ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ",
  "feedback_success": "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!"
  ,
  "demo_heading": "ಲೈವ್ ಡೆಮೊ ಬುಕ್ ಮಾಡಿ",
  "demo_subtitle": "ಸ್ವಲ್ಪ ವಿವರ ಹಂಚಿಕೊಳ್ಳಿ, ನಾವು ಶೀಘ್ರದಲ್ಲೇ ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.",
  "demo_name_label": "ನಿಮ್ಮ ಹೆಸರು",
  "demo_name_placeholder": "ರೋಹಿತ್ ಶರ್ಮಾ",
  "demo_hotel_label": "ಹೋಟೆಲ್/ಪ್ರಾಪರ್ಟಿ ಹೆಸರು",
  "demo_hotel_placeholder": "Sunrise Residency",
  "demo_email_label": "ಇಮೇಲ್",
  "demo_email_placeholder": "you@example.com",
  "demo_phone_label": "ಫೋನ್",
  "demo_phone_placeholder": "+91 98765 43210",
  "demo_city_label": "ನಗರ (ಐಚ್ಛಿಕ)",
  "demo_city_placeholder": "ಬೆಂಗಳೂರु",
  "demo_cancel": "ರದ್ದು",
  "demo_submit": "ಸಲ್ಲಿಸು",
  "demo_error_name": "ದಯವಿಟ್ಟು ಮಾನ್ಯ ಹೆಸರು ನಮೂದಿಸಿ",
  "demo_error_hotel": "ದಯವಿಟ್ಟು ಮಾನ್ಯ ಹೋಟೆಲ್ ಹೆಸರು ನಮೂದಿಸಿ",
  "demo_error_email": "ದಯವಿಟ್ಟು ಮಾನ್ಯ ಇಮೇಲ್ ನಮೂದಿಸಿ",
  "demo_error_phone": "ದಯವಿಟ್ಟು ಮಾನ್ಯ ಫೋನ್ ನಮೂದಿಸಿ",
  "demo_success_title": "ವಿನಂತಿ ಸ್ವೀಕೃತವಾಗಿದೆ",
  "demo_success_body": "ಧನ್ಯವಾದಗಳು! ಶೀಘ್ರದಲ್ಲೇ ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.",
  "demo_call_title": "ಮಾತನಾಡಲು ಇಷ್ಟವೇ?",
  "demo_call_hours": "ಎಲ್ಲಾ ದಿನಗಳು, ಬೆಳಗ್ಗೆ 9 – ಸಂಜೆ 5 ನಡುವೆ ಕರೆ ಮಾಡಿ",
  "demo_call_number_label": "ಕಾಲ್: {number}"
  },
  "mr": {
  // Navbar & common
  "nav_problem": "समस्या",
  "nav_solution": "उपाय",
  "nav_trusted": "विश्वास",
  "nav_demo": "डेमो",
  "nav_faq": "प्रश्न",
  "nav_about": "About",
  "nav_login": "लॉगिन",
  "nav_live_control": "Live Control",
  "lang_popup_title": "भाषा निवडा",
    "hero_title": "महसूल गळती थांबवा. प्रत्येक रुपया जतन करा.",
    "cta_call_label": "मोफत टेस्टिंगसाठी आत्ता कॉल करा",
    "cta_call_number": "+91 98765 43210",
    "cta_demo_label": "लाईव्ह डेमो बुक करा",
    "problem_heading": "कळतही नाही आणि पैसा जातोय?",
    "problem_points": [
      "रिसेप्शन रोख घेतो, PMS मध्ये नोंद नाही",
      "खोली वापरात, डॅशबोर्ड ‘Vacant’ दाखवतो",
      "मालकाचा महसूल शांतपणे कमी होतो"
    ],
    "solution_heading": "InnSync हे कसे सोडवते",
    "solution_points": [
      "प्रत्येक खोलीत मानवी उपस्थितीसाठी IoT सेन्सर",
      "डेटा रिअल-टाईममध्ये PMS डॅशबोर्डवर येतो",
      "अल्गोरिदम ऑक्युपन्सी-बुकिंग तफावत लगेच फ्लॅग करतो"
    ],
    "benefits_heading": "हॉटेल मालक InnSync का निवडतात",
    "benefits_points": [
      "पूर्ण दृश्यता: लाईव्ह ऑक्युपन्सी, बुकिंग आणि महसूल",
      "नोंद न झालेल्या मुक्कामांसाठी तत्काळ अलर्ट",
      "रोख व वॉक-इनमधील गळती थांबवा",
      "मुख्य बुकिंग प्लॅटफॉर्मसोबत कार्यरत"
    ],
    "how_heading": "कसे काम करते",
    "how_steps": [
      "OTAs आणि डायरेक्ट चॅनेल्समधून बुकिंग येतात",
      "सेन्सर रिअल-टाईममध्ये ऑक्युपन्सी शोधतात",
      "सिस्टम आपोआप डेटा जुळवते",
      "तफावत आढळल्यास मालकाला तत्काळ अलर्ट"
    ],
    "testimonial_heading": "आघाडीच्या हॉटेलमध्ये पायलटमध्ये",
    "testimonial_quote": "InnSync मुळे प्रॉपर्टीत काय चाललेय याचे स्पष्ट चित्र दिसते—आता ब्लाइंड स्पॉट नाही.",
    "testimonial_cite": "रोहित शर्मा, हॉटेल मालक, बेंगळुरू",
    "cta_repeat_heading": "InnSync लाईव्ह पाहण्यासाठी तयार?",
    "cta_repeat_body": "आत्ता कॉल करा—मोफत टेस्टिंग घ्या आणि किती बचत होऊ शकते ते पाहा.",
    "footer_tagline": "InnSync – प्रत्येक रुपया, प्रत्येक खोली, दररोज सुरक्षित.",
    "lang_label": "भाषा"
    ,
    "hero_badge": "🏨 स्मार्ट हॉटेल्सची निवड",
    "hero_subtitle": "InnSync एकमेव PMS—रिअल-टाईम IoT पडताळणीसह. एकही रुपया वाया नाही.",
    "hero_trust": "भारतातील 20+ हॉटेल्सचा विश्वास",
    "hero_pill1": "100% डेटा पारदर्शकता",
    "hero_pill2": "तत्काळ अलर्ट",
    "hero_pill3": "महसूल गळती थांबवा",
    // Live Control
    "live_title": "लाइव्ह कंट्रोल पॅनेल",
    "live_status_demo": "डेमो",
    "live_kpi_occupancy": "ऑक्युपन्सी",
    "live_kpi_registered": "रजिस्टर्ड",
    "live_kpi_leakage": "गळती",
    "live_alert_title": "लीक अलर्ट: 2 रूम व्यापल्या परंतु बुकिंग नाही",
    "live_alert_desc": "IoT सेन्सर: रूम 204, 311 • कृती आवश्यक",
    "live_bullets": [
      "IoT सेन्सर अनरिकॉर्डेड बुकिंग शोधतात",
      "प्रमुख OTA प्लॅटफॉर्मसोबत इंटिग्रेशन",
      "मालक/मॅनेजरसाठी सोपे डॅशबोर्ड"
    ],
    // Problem
    "problem_title": "समस्या",
    "problem_text": "खोली भरलेल्या, नोंदी रिकाम्या. वॉक-इनचा माग नाही. विजिबिलिटीशिवाय 10%+ महसूल गायब.",
    "problem_point1": "खोली वापरात पण नोंद नाही",
    "problem_point2": "अनट्रॅक्ड वॉक-इन आणि कर्मचारी चुका",
    "problem_point3": "डॅशबोर्ड व वास्तव जुळत नाही",
    "risk_title": "मासिक रिस्क स्नॅपशॉट",
    "risk_label1": "Unrecorded Nights",
    "risk_label2": "Monthly Loss",
    "risk_label3": "Occupancy Gap",
    // Solution & pricing
    "solution_title": "InnSync गळती कशी थांबवतो",
    "solution_tagline": "प्रत्येक बुकिंगची नोंद. रिअल-टाईम कंट्रोल. सुलभ ऑपरेशन्स.",
    "sol_card1_title": "IoT ऑक्युपन्सी सेन्सर",
    "sol_card1_desc": "अनरिकॉर्डेड स्टे त्वरित ओळखा—कॅमेरा/PII नाही.",
    "sol_card2_title": "सर्व OTA इंटिग्रेशन",
    "sol_card2_desc": "OYO, Booking.com, MMT, Agoda, Airbnb इत्यादींसोबत सिंक.",
    "sol_card3_title": "इंट्यूटिव डॅशबोर्ड",
    "sol_card3_desc": "ओनर्स व मॅनेजर्ससाठी लाईव्ह मेट्रिक्स.",
    "pricing_title": "प्रायसिंग",
    "pricing_headline": "फक्त ₹150/महिन्यासाठी 10%+ महसूल वाढ",
    "pricing_sub": "सरळ, पारदर्शक—लपलेले शुल्क नाही",
    "pricing_tag1": "लांब करार नाही",
    "pricing_tag2": "सोपे इन्स्टॉल",
    "pricing_tag3": "24×7 सपोर्ट",
    "call_now_btn": "आत्ता कॉल करा",
    "pricing_demo_btn": "फ्री डेमो बुक करा",
    // Trust & features
    "trust_title": "विश्वासासाठी तयार. परिणामांसाठी डिझाइन.",
    "trust_subtitle": "सिक्युरिटी, जबाबदारी आणि अपटाइम—हॉटेल्ससाठी विश्वासार्ह.",
    "trust_item1_title": "एंड-टू-एंड एन्क्रिप्शन",
    "trust_item1_desc": "ट्रान्झिट व रेस्ट",
    "trust_item2_title": "ओनर-फर्स्ट व्हिजिबिलिटी",
    "trust_item2_desc": "प्रत्येक रूम, दररोज",
    "trust_item3_title": "99.9% अपटाईम",
    "trust_item3_desc": "24×7 मॉनिटरिंग",
    "trust_item4_title": "ऑडिट लॉग्स",
    "trust_item4_desc": "प्रत्येक बदलाची साखळी",
    "ft_trio1_title": "60 सेकंदात लीक अलर्ट",
    "ft_trio1_desc": "सेन्सर ते फोन",
    "ft_trio2_title": "100% ऑडिट ट्रेल",
    "ft_trio2_desc": "प्रत्येक बदल नोंदवा",
    "ft_trio3_title": "ऑटो-रीकन्सिलिएशन",
    "ft_trio3_desc": "दैनिक OTA क्रॉस-चेक",
    // Trusted
    "trusted_title": "Trusted By",
    "trusted_subtitle": "आघाडीचे हॉस्पिटॅलिटी ब्रँड InnSync वापरतात",
    // Demo
    "demo_title": "फ्री डेमो बुक करा",
    "demo_subtitle": "तुमच्या प्रॉपर्टीबद्दल सांगा—InnSync कसा उपयोगी आहे ते पाहा.",
    "demo_name_label": "तुमचे नाव",
    "demo_phone_label": "फोन",
    "demo_hotel_label": "हॉटेल / प्रॉपर्टी नाव",
    "demo_submit_label": "डेमो रिक्वेस्ट करा",
    "demo_or_call_text": "किंवा थेट कॉल करा",
    "demo_success": "धन्यवाद! डेमो शेड्यूल करण्यासाठी आम्ही संपर्क करू.",
    "how_timeline": [
      {"title": "कनेक्ट करा", "desc": "InnSync शी हॉटेल काही मिनिटांत जोडा—कोणतीही तांत्रिक गरज नाही.", "icon": "🔗"},
      {"title": "शोधा", "desc": "IoT सेन्सर खरी उपस्थिती शोधतात आणि डॅशबोर्डवर पाठवतात.", "icon": "📡"},
      {"title": "पडताळा", "desc": "आमचा अल्गोरिदम बुकिंग आणि उपस्थिती जुळवतो व तफावत लगेच दाखवतो.", "icon": "🤖"},
      {"title": "अलर्ट", "desc": "नोंद न झालेल्या मुक्कामांसाठी किंवा संशयास्पद कृतीसाठी तत्काळ अलर्ट मिळवा.", "icon": "⚡"}
    ],
    "testimonial_heading": "आमचे ग्राहक काय म्हणतात",
    "testimonials": [
      {"quote": "InnSync मुळे प्रॉपर्टीत काय चाललेय याचे स्पष्ट चित्र दिसते—आता ब्लाइंड स्पॉट नाही.", "cite": "रोहित शर्मा, हॉटेल मालक, बेंगळुरू"},
      {"quote": "महसूल गळती शून्यावर आली. अलर्ट्स अप्रतिम आहेत!", "cite": "प्रिया देसाई, ब्लू लॅगून"},
      {"quote": "सेटअप खूप सोपे, आता हॉटेलच्या महसूलवर पूर्ण नियंत्रण आहे.", "cite": "अमित वर्मा, अर्बन नेस्ट"},
      {"quote": "IoT पडताळणीमुळे ऑक्युपन्सीवरचे वाद संपले.", "cite": "सीमा कपूर, रॉयल स्टे"},
      {"quote": "अलर्ट्समुळे टीम लगेच कृती करते—आता मॅन्युअल फॉलो-अप नाही.", "cite": "विक्रम राव, फ्रंट ऑफिस मॅनेजर"},
      {"quote": "पहिल्याच आठवड्यात राहिलेला महसूल परत मिळाला.", "cite": "नेहा गुप्ता, मालक, पुणे"},
      {"quote": "आमच्या PMS सोबत इंटीग्रेशन अगदी सुरळीत झाले.", "cite": "करण मेहता, जीएम, बीचसाइड इन"},
      {"quote": "डॅशबोर्ड साधा आहे आणि जे महत्त्वाचे तेच दाखवतो.", "cite": "अनिता अय्यर, बुटीक हॉटेल"},
      {"quote": "InnSync ची किंमत वसूल—गळती थांबली.", "cite": "राहुल जैन, बहु-प्रॉपर्टी मालक"}
    ],
    "login_title": "डेमोमध्ये लॉगिन करा",
    "login_subtitle": "नमुना क्रेडेन्शियल वापरा:",
    "login_email_label": "ईमेल",
    "login_password_label": "पासवर्ड",
    "login_owner_btn": "मालक म्हणून लॉगिन करा",
    "login_manager_btn": "मॅनेजर म्हणून लॉगिन करा",
  "login_terms": "लॉगिन करून तुम्ही डेमो अटींना सहमती देता. डेटा केवळ डेमो साठी आहे.",
  "feature1_title": "IoT-चालित खोली निरीक्षण",
  "feature1_desc": "स्मार्ट सेन्सर खरी उपस्थिती ट्रॅक करतात, फक्त बुकिंग नाही.",
  "feature2_title": "तत्काळ महसूल अलर्ट",
  "feature2_desc": "तफावत किंवा गळती मिळताच त्वरित सूचना मिळते.",
  "feature3_title": "मालक-प्रथम डॅशबोर्ड",
  "feature3_desc": "लाईव्ह ऑक्युपन्सी, बुकिंग आणि महसूल एकाच ठिकाणी पहा.",
  "usecase1_title": "प्रत्येक वॉक-इन पकडा",
  "usecase1_desc": "आता कोणताही अनरिकॉर्डेड मुक्काम नाही—प्रत्येक पाहुणा आपोआप ट्रॅक होतो.",
  "usecase2_title": "मालक नियंत्रण",
  "usecase2_desc": "मालकांना त्वरित अलर्ट आणि पूर्ण दृश्यता, कुठूनही.",
  "usecase3_title": "सोपे इंटीग्रेशन",
  "usecase3_desc": "तुमच्या विद्यमान PMS आणि बुकिंग प्लॅटफॉर्मसोबत कार्य करते.",
  "faq_heading": "वारंवार विचारले जाणारे प्रश्न",
  "faq_q1": "InnSync महसूल गळती कशी थांबवतो?",
  "faq_a1": "InnSync IoT सेन्सर आणि स्मार्ट अल्गोरिदम वापरून खरी उपस्थिती आणि बुकिंग जुळवतो, आणि त्वरित तफावत दाखवतो.",
  "faq_q2": "InnSync हॉटेलमध्ये बसवणे सोपे आहे का?",
  "faq_a2": "हो! बहुतेक हॉटेल्स 30 मिनिटांत सुरू होतात. कोणतीही तांत्रिक गरज नाही.",
  "faq_q3": "InnSync माझ्या PMS सोबत काम करतो का?",
  "faq_a3": "InnSync प्रमुख PMS आणि बुकिंग प्लॅटफॉर्मसोबत इंटीग्रेट होतो. अधिक माहितीसाठी संपर्क करा.",
  "feedback_heading": "तुमचे अभिप्राय शेअर करा",
  "feedback_label": "तुमचा अभिप्राय आम्हाला सुधारण्यास मदत करतो:",
  "feedback_placeholder": "तुमचे विचार, सूचना किंवा प्रश्न येथे लिहा...",
  "feedback_submit": "अभिप्राय पाठवा",
  "feedback_success": "तुमच्या अभिप्रायाबद्दल धन्यवाद!"
  ,
  "demo_heading": "लाईव्ह डेमो बुक करा",
  "demo_subtitle": "काही तपशील शेअर करा, आम्ही वेळ ठरवण्यासाठी संपर्क करू.",
  "demo_name_label": "तुमचे नाव",
  "demo_name_placeholder": "रोहित शर्मा",
  "demo_hotel_label": "हॉटेल/प्रॉपर्टी नाव",
  "demo_hotel_placeholder": "Sunrise Residency",
  "demo_email_label": "ईमेल",
  "demo_email_placeholder": "you@example.com",
  "demo_phone_label": "फोन",
  "demo_phone_placeholder": "+91 98765 43210",
  "demo_city_label": "शहर (पर्यायी)",
  "demo_city_placeholder": "बेंगळुरू",
  "demo_cancel": "रद्द",
  "demo_submit": "सबमिट",
  "demo_error_name": "कृपया वैध नाव टाका",
  "demo_error_hotel": "कृपया वैध हॉटेल नाव टाका",
  "demo_error_email": "कृपया वैध ईमेल टाका",
  "demo_error_phone": "कृपया वैध फोन नंबर टाका",
  "demo_success_title": "विनंती प्राप्त झाली",
  "demo_success_body": "धन्यवाद! आम्ही लवकरच संपर्क करू.",
  "demo_call_title": "फोनवर बोलणे पसंत आहे?",
  "demo_call_hours": "दररोज, सकाळी 9 – संध्याकाळी 5 दरम्यान कॉल करा",
  "demo_call_number_label": "कॉल करा {number}"
  }
};

// Export for use in HTML
window.languageContent = languageContent;
